[package]
name = "SportsBetting"
version = "1.0.0"
authors = []

[addresses]
sports_betting = "0xc90dabb5730415a099ff16d8edf5a3a350ff28d3183e2ecb80182312cc99d5cb"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

