app = "sports-move-job"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PRODUCTION_URL = "https://sports-move.vercel.app"
  TZ = "America/New_York"

[[restart]]
  policy = "always"
  max_retries = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
